/**
 * @file src/actions/habit.ts
 * @description Astro Actions for the habit tracker feature.
 *
 * These are the only entry points for habit data mutations from the client.
 * Each action validates its input with Zod, verifies the user session,
 * and delegates to the appropriate mutation function in @/lib/habit/mutations.
 *
 * Actions are registered in src/actions/index.ts under the `habit` key.
 *
 * @example
 * // In a client-side script or island:
 * import { actions } from "astro:actions";
 *
 * const { data, error } = await actions.habit.create({
 *   name: "Morning meditation",
 *   tracking_type: "boolean",
 * });
 */

import { defineAction, ActionError } from "astro:actions";
import { z } from "astro/zod";
import { createClient } from "@/lib/supabase";
import {
  createHabit,
  updateHabit,
  deleteHabit,
  createHabitLog,
  upsertHabitLog,
  updateHabitLog,
  deleteHabitLog,
} from "@/lib/habit/mutations";

/**
 * The Json type is generated by `pnpm db:types` from your Supabase schema.
 * It represents any value that can be stored in a Postgres jsonb column.
 * We import it here so TypeScript knows that our `metadata` input is
 * compatible with what Supabase expects — without this cast, TypeScript
 * sees Record<string, unknown> and Json as incompatible even though they
 * describe the same shape at runtime.
 */
import type { Json } from "@/types/supabase";

// ─── Shared Schemas ───────────────────────────────────────────────────────────

/**
 * The allowed tracking types for a habit.
 * Matches the TrackingType union in @/lib/habit/types.ts.
 */
const trackingTypeSchema = z.enum(["boolean", "count", "duration"]);

/**
 * A date string in YYYY-MM-DD format.
 * Validated with a regex to match Postgres date column format.
 */
const dateStringSchema = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, "Date must be in YYYY-MM-DD format");

// ─── Session Helper ───────────────────────────────────────────────────────────

/**
 * Retrieves the authenticated user from the current Supabase session.
 * Throws an UNAUTHORIZED ActionError if no session is found.
 *
 * @param context - The Astro action handler context.
 * @returns The authenticated Supabase user object and a ready supabase client.
 * @throws {ActionError} UNAUTHORIZED if the user is not logged in.
 */
async function getAuthenticatedUser(context: Parameters<Parameters<typeof defineAction>[0]["handler"]>[1]) {
  const supabase = createClient({
    request: context.request,
    cookies: context.cookies,
  });

  const { data: { user }, error } = await supabase.auth.getUser();

  if (error || !user) {
    throw new ActionError({
      code: "UNAUTHORIZED",
      message: "You must be logged in to perform this action.",
    });
  }

  return { supabase, user };
}

// ─── Habit Actions ────────────────────────────────────────────────────────────

export const habit = {
  /**
   * Creates a new habit for the authenticated user.
   *
   * @input name - The display name of the habit.
   * @input tracking_type - How the habit is tracked: boolean, count, or duration.
   * @input metadata - Optional key/value data (e.g. target count, unit label).
   */
  create: defineAction({
    input: z.object({
      name: z.string().min(1, "Habit name is required").max(100),
      tracking_type: trackingTypeSchema.default("boolean"),
      // z.record() in Zod 4 requires an explicit key type as the first argument
      metadata: z.record(z.string(), z.unknown()).optional(),
    }),
    handler: async (input, context) => {
      const { supabase, user } = await getAuthenticatedUser(context);

      const { data, error } = await createHabit(supabase, {
        name: input.name,
        tracking_type: input.tracking_type,
        // Cast metadata to Json so TypeScript knows it's compatible with
        // Supabase's jsonb column type. Safe at runtime — both are plain objects.
        metadata: (input.metadata ?? null) as Json | null,
        user_id: user.id,
      });

      if (error) {
        throw new ActionError({
          code: "INTERNAL_SERVER_ERROR",
          message: error.message,
        });
      }

      return data;
    },
  }),

  /**
   * Updates an existing habit by ID.
   * Only the authenticated owner can update their own habits.
   *
   * @input id - The UUID of the habit to update.
   * @input name - Optional new display name.
   * @input tracking_type - Optional new tracking type.
   * @input metadata - Optional new metadata.
   */
  update: defineAction({
    input: z.object({
      id: z.uuid("Invalid habit ID"),
      name: z.string().min(1).max(100).optional(),
      tracking_type: trackingTypeSchema.optional(),
      metadata: z.record(z.string(), z.unknown()).optional(),
    }),
    handler: async (input, context) => {
      const { supabase, user } = await getAuthenticatedUser(context);

      // Separate metadata from the rest of the update fields so we can
      // cast it to Json independently without affecting the other fields.
      const { id, metadata, ...rest } = input;

      const { data, error } = await updateHabit(supabase, id, user.id, {
        ...rest,
        // Only include metadata in the update if it was actually provided.
        // The spread with a conditional avoids sending `metadata: undefined`
        // to Supabase, which would overwrite existing data with null.
        ...(metadata !== undefined && { metadata: metadata as Json }),
      });

      if (error) {
        throw new ActionError({
          code: "INTERNAL_SERVER_ERROR",
          message: error.message,
        });
      }

      return data;
    },
  }),

  /**
   * Deletes a habit and all its associated log entries.
   * Only the authenticated owner can delete their own habits.
   *
   * @input id - The UUID of the habit to delete.
   */
  delete: defineAction({
    input: z.object({
      id: z.uuid("Invalid habit ID"),
    }),
    handler: async (input, context) => {
      const { supabase, user } = await getAuthenticatedUser(context);

      const { error } = await deleteHabit(supabase, input.id, user.id);

      if (error) {
        throw new ActionError({
          code: "INTERNAL_SERVER_ERROR",
          message: error.message,
        });
      }

      return { success: true };
    },
  }),

  // ─── Habit Log Actions ────────────────────────────────────────────────────

  /**
   * Logs a habit completion for a specific date.
   * Use this when you know no log exists for the date yet.
   * Prefer upsertLog when you're not sure — it handles both cases.
   *
   * @input habit_id - The UUID of the habit to log.
   * @input entry_date - The date to log (YYYY-MM-DD).
   * @input value - Optional numeric value (for count/duration habits).
   * @input note - Optional note for this log entry.
   */
  logEntry: defineAction({
    input: z.object({
      habit_id: z.uuid("Invalid habit ID"),
      entry_date: dateStringSchema,
      value: z.number().optional(),
      note: z.string().max(500).optional(),
    }),
    handler: async (input, context) => {
      const { supabase, user } = await getAuthenticatedUser(context);

      const { data, error } = await createHabitLog(supabase, {
        habit_id: input.habit_id,
        entry_date: input.entry_date,
        value: input.value ?? null,
        note: input.note ?? null,
        user_id: user.id,
      });

      if (error) {
        throw new ActionError({
          code: "INTERNAL_SERVER_ERROR",
          message: error.message,
        });
      }

      return data;
    },
  }),

  /**
   * Upserts a habit log — inserts if no entry exists for that date,
   * updates if one already does. This is the preferred action for the
   * daily check-in UI where you don't want to pre-check for an existing log.
   *
   * Requires a unique constraint on (habit_id, entry_date) in Postgres.
   *
   * @input habit_id - The UUID of the habit to log.
   * @input entry_date - The date to log (YYYY-MM-DD).
   * @input value - Optional numeric value (for count/duration habits).
   * @input note - Optional note for this log entry.
   */
  upsertLog: defineAction({
    input: z.object({
      habit_id: z.uuid("Invalid habit ID"),
      entry_date: dateStringSchema,
      value: z.number().optional(),
      note: z.string().max(500).optional(),
    }),
    handler: async (input, context) => {
      const { supabase, user } = await getAuthenticatedUser(context);

      const { data, error } = await upsertHabitLog(supabase, {
        habit_id: input.habit_id,
        entry_date: input.entry_date,
        value: input.value ?? null,
        note: input.note ?? null,
        user_id: user.id,
      });

      if (error) {
        throw new ActionError({
          code: "INTERNAL_SERVER_ERROR",
          message: error.message,
        });
      }

      return data;
    },
  }),

  /**
   * Updates an existing habit log entry by ID.
   *
   * @input id - The UUID of the log entry to update.
   * @input value - Optional new numeric value.
   * @input note - Optional new note.
   */
  updateLog: defineAction({
    input: z.object({
      id: z.uuid("Invalid log ID"),
      value: z.number().optional(),
      note: z.string().max(500).optional(),
    }),
    handler: async (input, context) => {
      const { supabase, user } = await getAuthenticatedUser(context);

      const { id, ...updates } = input;

      const { data, error } = await updateHabitLog(supabase, id, user.id, updates);

      if (error) {
        throw new ActionError({
          code: "INTERNAL_SERVER_ERROR",
          message: error.message,
        });
      }

      return data;
    },
  }),

  /**
   * Deletes a habit log entry by ID.
   * Used when a user wants to un-check a habit for a given day.
   *
   * @input id - The UUID of the log entry to delete.
   */
  deleteLog: defineAction({
    input: z.object({
      id: z.uuid("Invalid log ID"),
    }),
    handler: async (input, context) => {
      const { supabase, user } = await getAuthenticatedUser(context);

      const { error } = await deleteHabitLog(supabase, input.id, user.id);

      if (error) {
        throw new ActionError({
          code: "INTERNAL_SERVER_ERROR",
          message: error.message,
        });
      }

      return { success: true };
    },
  }),
};